### ISSUE TITLE
Add more complete information to reco_config API

### ISSUE THREAD

**Issue by davidlange6** [dmwm/t0wmadatasvc#30]
Hi-
I notice that one can not determine a few things in the TIer0 config from the reco API  Eg
- what data tiers are produced 
- how many threads

are these derivable somewhere else?

**Comment by hufnagel** [comment]
No, since neither of these affect the physics content of the PromptReco output (and keeping a record of the reco config so far was only to be able to reproduce the physics output of PromptReco).
If you want to be able to know operationally what these settings were for a given run in the past, this information doesn't really exist. You can look at the Tier0 configs in github and/or cmsweb to see the current settings, that's it.

**Comment by davidlange6** [comment]
hi @hufnagel - thanks for the answer. In current software, its instead "neither of these _should_ affect the physics content", as there can be threading bugs and what actually runs from a configuration depends on its output.

It would be useful if these were tracked for 2018 data.

**Comment by hufnagel** [comment]
Code has been written, patch for the Tier0 is available and has been handed to Tier0Ops.

Patch for the Tier0 Data Service to return this information has been written, but needs to be tested. Should make it into the next cmsweb deployment cycle.
